# .github/workflows/build.yml
name: Build Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
  pull_request:
    paths-ignore:
      - .github/**
      - README.md

permissions:
  contents: read

jobs:
  build-x86_64:
    if: "!startsWith(github.event.head_commit.message, 'Merge pull request')"
    name: "Build Bundle (${{ matrix.variant.label }}, x86_64)"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - pkg: unwrapped
            label: full
          - pkg: mini
            label: mini

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up post build hook
      run: |
        cat > /tmp/post-build-hook.sh << EOF
        set -euf
        if [ -n "$OUT_PATHS" ]; then
        echo "Uploading paths" $OUT_PATHS
        NIX_SSHOPTS="-o StrictHostKeyChecking=no" nix copy --to "ssh://nixremote@mingzhu" $OUT_PATHS
        fi
        EOF
        chmod +x /tmp/post-build-hook.sh
          
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-26.05
        extra_nix_config: |
          extra-substituters = http://cache.crys
          extra-trusted-public-keys = mingzhu:V0KsUipFnrBNsfUD8VI0rFXQpgE3KKJfRby9Jm8cLTQ=
          connect-timeout = 30
          fallback = true
          post-build-hook = /tmp/post-build-hook.sh
          access-tokens = github.com=${{ secrets.GH_TOKEN }}

    - name: Build
      run: |
        nix bundle --bundler .#simple -o bundle .#${{ matrix.variant.pkg }} -L 2>&1

    - name: Upload Nix build artifacts
      uses: https://github.com/christopherHX/gitea-upload-artifact@v4
      with:
        name: "sanzenvim-${{ matrix.variant.label }}-x86_64"
        path: |
          bundle/bin/nvim

  build-aarch64:
    if: "!startsWith(github.event.head_commit.message, 'Merge pull request')"
    name: "Build Bundle (${{ matrix.variant.label }}, aarch64)"
    runs-on: ubuntu-latest-arm
    strategy:
      fail-fast: false
      matrix:
        variant:
          - pkg: unwrapped
            label: full
          - pkg: mini
            label: mini

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up post build hook
      run: |
        cat > /tmp/post-build-hook.sh << EOF
        set -euf
        if [ -n "$OUT_PATHS" ]; then
        echo "Uploading paths" $OUT_PATHS
        NIX_SSHOPTS="-o StrictHostKeyChecking=no" nix copy --to "ssh://nixremote@mingzhu" $OUT_PATHS
        fi
        EOF
        chmod +x /tmp/post-build-hook.sh
          
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-26.05
        extra_nix_config: |
          extra-substituters = http://cache.crys
          extra-trusted-public-keys = mingzhu:V0KsUipFnrBNsfUD8VI0rFXQpgE3KKJfRby9Jm8cLTQ=
          connect-timeout = 30
          fallback = true
          post-build-hook = /tmp/post-build-hook.sh
          access-tokens = github.com=${{ secrets.GH_TOKEN }}

    - name: Build
      run: |
        nix bundle --bundler .#simple -o bundle .#${{ matrix.variant.pkg }} -L 2>&1

    - name: Upload Nix build artifacts
      uses: https://github.com/christopherHX/gitea-upload-artifact@v4
      with:
        name: "sanzenvim-${{ matrix.variant.label }}-aarch64"
        path: |
          bundle/bin/nvim
