name: Export Pure Lua Config

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
  pull_request:
    paths-ignore:
      - .github/**
      - README.md

permissions:
  contents: read

jobs:
  wake-up-emily:
    name: Wake up emily
    if: "!startsWith(github.event.head_commit.message, 'Merge pull request')"
    runs-on: native-arm

    steps:
      - name: Call HA webhook
        run: curl -X PUT http://dorm.crys/api/webhook/wake-up-emily

  export:
    name: "Export init.lua (${{ matrix.runner.arch }})"
    needs: wake-up-emily
    if: "!startsWith(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ${{ matrix.runner.tag }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - arch: x86_64
            tag: ubuntu-latest
          - arch: aarch64
            tag: ubuntu-latest-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-26.05
          extra_nix_config: |
            substituters = http://cache.crys
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nixpkgs-python.cachix.org-1:hxjI7pFxTyuTHn2NkvWCrAUcNZLNS3ZAvfYNuYifcEU= cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M= lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964= itscrystalline.cachix.org-1:w+aEu6k5Rx3xgUSJPCUhdZSxS919ZJvv9wThPKGVMv4= vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4= harmonia.cache.crys:5IjKpw7rA9DxB2BVvDY/NzD0Zakjn9t9SB40AEpY2Q8=
            access-tokens = github.com=${{ secrets.GH_TOKEN }}

      - name: Build
        run: |
          nix build .#lua -L
          mkdir -p ./export
          cp -R ./result/. ./export/

      - name: Upload exported Lua config
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: sanzenvim-lua-${{ matrix.runner.arch }}
          path: |
            export/init.lua
            export/sanzenvim.generated.lua
            export/pack

      - name: Install remote store SSH key
        run: |
          echo ${{ secrets.MINGZHU_PRIVKEY_NIXREMOTE_BASE64 }} | base64 --decode > /tmp/nixremote
          chmod 400 /tmp/nixremote
          wc /tmp/nixremote

      - name: Upload to binary cache
        run: |
          NIX_SSHOPTS="-o StrictHostKeyChecking=no -i /tmp/nixremote" nix copy --substitute-on-destination --to "ssh://nixremote@mingzhu" ./result
