name: Update flake lockfile

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3,6"

permissions:
  contents: write

jobs:
  build:
    name: "update flake lockfiles & upload to my binary cache"
    runs-on: ${{ matrix.platform.on }}
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - on: ubuntu-latest 
            name: x86_64
          - on: ubuntu-24.04-arm 
            name: aarch64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-25.11
        extra_nix_config: |
          extra-substituters = http://cache.crys
          extra-trusted-public-keys = mingzhu:V0KsUipFnrBNsfUD8VI0rFXQpgE3KKJfRby9Jm8cLTQ=
          connect-timeout = 30
          stall-timeout = 600
          fallback = true

    - name: Update flake inputs
      run: nix flake update

    - name: Build
      id: build
      run: |
        outpath=$(nix build .# --no-link --print-out-paths -L)
        echo "outpath=${outpath}" >> "$GITHUB_OUTPUT"
        echo "Output path: ${outpath}"

    - name: Upload Nix build artifacts to cache
      env: 
        OUTPATH: ${{ steps.build.outputs.outpath }}
      run: NIX_SSHOPTS="-o StrictHostKeyChecking=no" nix copy --to "ssh://nixremote@mingzhu" $OUTPATH

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        push: true
        message: 'chore: update flake (automated)'
