name: Update flake lockfile

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3,6"

jobs:
  build:
    name: "update flake lockfiles"
    runs-on: ubuntu-latest-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-26.05
        extra_nix_config: |
          extra-substituters = http://cache.crys
          extra-trusted-public-keys = mingzhu:V0KsUipFnrBNsfUD8VI0rFXQpgE3KKJfRby9Jm8cLTQ=
          connect-timeout = 30
          fallback = true
          access-tokens = github.com=${{ secrets.GH_TOKEN }}

    - name: Update flake.lock
      id: update
      run: |
        nix flake update 2> >(tee /dev/stderr) | awk '
          /^• Updated input/ {in_update = 1; print; next}
          in_update && !/^warning:/ {print}
          /^$/ {in_update = 0}
        ' > update.log

        echo "UPDATE_LOG<<EOF" >> $GITHUB_ENV
        cat update.log >> $GITHUB_ENV 
        echo "EOF" >> $GITHUB_ENV

        rm update.log

    - name: Write PR body template
      uses: https://github.com/DamianReeves/write-file-action@v1.3
      with:
        path: pr_body.template
        contents: |
          automatically updated:

          ```
          ${{ env.UPDATE_LOG }}
          ```

    - name: Generate PR body
      uses: pedrolamas/handlebars-action@v2.4.0 # v2.4.0
      with:
        files: "pr_body.template"
        output-filename: "pr_body.md"
    - name: Save PR body
      id: pr_body
      uses: juliangruber/read-file-action@v1
      with:
        path: "pr_body.md"

    - name: Remove temporary files
      run: |
        rm pr_body.template
        rm pr_body.md

    - uses: EndBug/add-and-commit@v10 # You can change this to use a specific version.
      with:
        author_name: crystals forgojo actions runner
        author_email: runner@git.iw2tryhard.dev
        message: |
          automated: Update `flake.lock`

          ${{ steps.pr_body.outputs.content }}
        new_branch: update-flake-lock 

    - name: Install tea
      run: nix profile install nixpkgs#tea

    - name: Create Pull Request
      id: create-pull-request
      uses: https://git.theless.one/actions/create-pr@main
      with:
        source-branch: update-flake-lock
        title: 'chore: Update flake (automated)'
        description: ${{ steps.pr_body.outputs.content }}
        token: ${{ secrets.FJ_TOKEN }}
        user: itscrystalline
        auto-merge: true
        delete-branch: true

    - name: PR number
      run: echo "PR \#${{ steps.create-pull-request.outputs.pr }}"
